POST http://localhost:3000/registro
content-Type: application/json

{
  "nombre": "Maria",
  "mensaje": "Hola comunidad"
}

### incidencia 
POST http://localhost:3000/incidencia
content-Type: application/json

{
  "tipo": "Seguridad en la ciudad",
  "descripcion": "La comunidad informa que en la comuna 1 hay una balacera entre diferentes bandas criminales."
}

